name: Go package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Get Go Version
        run: go version

      - name: Install dependencies
        run: |
            go get .
      
      - name: Build
        run: go build -v -o go-be-cli ./main.go

      - name: list all
        run: ls

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fradidock/kub-train-be-cli
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}        
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short                
        
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          build-args: PROJECT_VERSION="$PROJECT_VERSION"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



  

          

